# docker-compose.yml - infrastructure locale
services:
  rabbitmq:
    # Broker local pour les evenements entre room-service et booking-service.
    image: rabbitmq:3-management
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI -> http://localhost:15672
    environment:
      RABBITMQ_DEFAULT_USER: cowork
      RABBITMQ_DEFAULT_PASS: cowork

  rooms-db:
    image: postgres:15
    environment:
      POSTGRES_DB: rooms_db
      POSTGRES_USER: cowork
      POSTGRES_PASSWORD: cowork
    ports:
      - "5435:5432"

  bookings-db:
    image: postgres:15
    environment:
      POSTGRES_DB: bookings_db
      POSTGRES_USER: cowork
      POSTGRES_PASSWORD: cowork
    ports:
      - "5434:5432"
